### ISSUE TITLE
Custom model integration

### ISSUE THREAD

**Issue by jp3spinelli** [samirsogay/face-tracking-raspberry-pi#1]
I am trying to use this to get my pan/tilt hat to track an opposing Raspberry Pi camera. I have trained my custom model and converted it to TFlite. It detects fine, I just need to know how to integrate my model into this repository to be able to track.
Thanks!

**Comment by samirsogay** [comment]
In any one of the file, there are 2 parts. One part does detection and another does pan tilt to get camera to centre. Replace the first part with your tflite detection and use the location coordinates in the second part to centre the camera.
